import { useState } from 'react';

type Conversation = { id:number; name:string; channel:string; preview:string; time:string; unread:number; status:string };
const initial:Conversation[]=[
{id:1,name:'Priya Sharma',channel:'WhatsApp',preview:'Hi, I wanted to know more about the course.',time:'10:42 AM',unread:2,status:'open'},
{id:2,name:'Rahul Kumar',channel:'Instagram',preview:'Can you share the pricing details?',time:'9:18 AM',unread:1,status:'open'},
{id:3,name:'Meera Nair',channel:'Email',preview:'Thank you for the information.',time:'Yesterday',unread:0,status:'closed'},
];
export default function Inbox(){const [items,setItems]=useState(initial);const [active,setActive]=useState(1);const [text,setText]=useState('');const current=items.find(x=>x.id===active)??items[0];const send=()=>{if(!text.trim())return;setItems(x=>x.map(c=>c.id===active?{...c,preview:text,time:'Just now',unread:0}:c));setText('')};return <main className="inbox-page"><header className="inbox-head"><div><p className="eyebrow">MESSAGING</p><h1>Inbox</h1><p className="muted">Manage every customer conversation from one place.</p></div><button className="primary">+ New conversation</button></header><section className="inbox-shell"><aside className="conversation-list"><div className="inbox-tools"><input placeholder="Search conversations…"/><select><option>All channels</option><option>WhatsApp</option><option>Instagram</option><option>Email</option></select></div>{items.map(c=><button className={`conversation ${active===c.id?'selected':''}`} onClick={()=>setActive(c.id)} key={c.id}><span className="avatar">{c.name.split(' ').map(x=>x[0]).join('')}</span><span className="conversation-copy"><strong>{c.name}</strong><small>{c.channel} · {c.preview}</small></span><span className="conversation-meta"><small>{c.time}</small>{c.unread>0&&<b>{c.unread}</b>}</span></button>)}</aside><article className="chat"><div className="chat-head"><div className="person"><span className="avatar">{current.name.split(' ').map(x=>x[0]).join('')}</span><div><strong>{current.name}</strong><small>{current.channel} · Active conversation</small></div></div><div className="chat-actions"><button>Assign</button><button>⋯</button></div></div><div className="messages"><div className="date">Today</div><div className="bubble incoming">Hi, I wanted to know more about the course.<small>10:42 AM</small></div><div className="bubble outgoing">Absolutely! I can help you with the details. Which course are you interested in?<small>10:43 AM · Delivered</small></div></div><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Write a reply…"/><div className="composer-row"><div className="composer-tools"><button>＋</button><button>😊</button><button>AI Assist</button></div><button className="primary" onClick={send}>Send</button></div></div></article><aside className="customer-panel"><div className="customer-avatar">{current.name.split(' ').map(x=>x[0]).join('')}</div><h2>{current.name}</h2><p>{current.channel} contact</p><hr/><dl><dt>Phone</dt><dd>+91 98765 43210</dd><dt>Email</dt><dd>customer@example.com</dd><dt>Company</dt><dd>Acme Studio</dd></dl><button className="secondary full">View contact</button></aside></section></main>}
